```{r}
library(rstan)
install.packages("shinystan")
library(shinystan)
library(dplyr)
library(tidyverse)

setwd('/Users/1thaliaespana1/Documents/Semestre II/ambientes/sandbox_Python/bayesian_glm/draft')

df <- read.csv("credito_mlg_mcd.csv",encoding="Latin-1") #|> select(tasa_ponderada,pct_enganche,dat_ai_edad_acred,dl_generoMasculino)

df$tasa_ponderada <- as.numeric(df$tasa_ponderada)
df$pct_enganche <- as.numeric(df$pct_enganche)

```

# Modelo 1
```{r}
model <- stan_model("model_1.stan")


stan_data <- list(
  N = nrow(df),
  tasa_ponderada = df$tasa_ponderada,
  pct_enganche = df$pct_enganche
)


fit <- sampling(
  model, 
  data = stan_data,
  thin = 6,
  chains = 2,
  warmup=2000,
  iter = 10000,
  seed=4595,
  # algorithm="HMC"
  )

saveRDS(fit, file = "model_1.rds")

loaded_fit <- readRDS(file = "model_1.rds")
launch_shinystan(loaded_fit)


# summary(fit)
# plot(fit)
# traceplot(fit)
# traceplot(fit, pars = c("alpha", "beta"),  nrow = 2)
# print(fit)

````

# Modelo 2
```{r}
df$tasa_ponderada <- as.numeric(df$tasa_ponderada)
df$pct_enganche <- as.numeric(df$pct_enganche)
df$dat_ai_edad_acred <- as.numeric(df$dat_ai_edad_acred)

model <- stan_model("model_2.stan")

stan_data <- list(
  N = nrow(df),
  tasa_ponderada = df$tasa_ponderada,
  pct_enganche = df$pct_enganche,
  dat_ai_edad_acred = df$dat_ai_edad_acred
)


fit <- sampling(
  model, 
  data = stan_data,
  thin = 5,
  chains = 2,
  warmup=2000,
  iter = 10000,
  seed=4595,
  # algorithm="HMC"
)

saveRDS(fit, file = "model_2.rds")

loaded_fit <- readRDS(file = "model_2.rds")
launch_shinystan(loaded_fit)

```

# Modelo 3
```{r}
```
# Modelo 4
```{r}
library(caret)
dummy <- dummyVars(" ~ .", data=df)
final_df <- data.frame(predict(dummy, newdata=df))

final_df$tasa_ponderada <- as.numeric(final_df$tasa_ponderada)
final_df$dl_generoMasculino <- as.numeric(final_df$dl_generoMasculino)
final_df$dat_ai_edad_acred <- as.numeric(final_df$dat_ai_edad_acred)
final_df$pct_enganche <- as.numeric(final_df$pct_enganche)

model <- stan_model("model_4.stan")

stan_data <- list(
  N = nrow(final_df),
  tasa_ponderada = final_df$tasa_ponderada,
  dl_generoMasculino = final_df$dl_generoMasculino,
  dat_ai_edad_acred = final_df$dat_ai_edad_acred,
  pct_enganche = final_df$pct_enganche
)

fit <- sampling(
  model, 
  data = stan_data,
  thin = 1,
  chains = 2,
  warmup=1000,
  iter = 5000,
  seed=4595,
  # algorithm="HMC"
)

saveRDS(fit, file = "model_4.rds")

loaded_fit <- readRDS(file = "model_4.rds")
launch_shinystan(loaded_fit)
```
